CREATE TABLE staging.mep_word_persistence (
  rev_id INT,
  rev_timestamp VARBINARY(20),
  page_id INT,
  page_namespace INT,
  page_title VARBINARY(255),
  user_id INT,
  user_text VARBINARY(255),
  comment VARBINARY(255),
  minor TINYINT,
  sha1 VARCHAR(32),
  revisions_processed INT,
  non_self_processed INT,
  seconds_possible INT,
  tokens_added INT,
  persistent_tokens INT,
  non_self_persistent_tokens INT,
  censored TINYINT,
  non_self_censored TINYINT,
  sum_log_persisted FLOAT,
  sum_log_non_self_persisted FLOAT,
  sum_log_seconds_visible FLOAT,
  PRIMARY KEY(rev_id)
);
